# Generated by Django 4.1 on 2023-08-30 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePrefs',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('sel_type_01', models.IntegerField()),
                ('sel_type_02', models.IntegerField()),
                ('sel_type_03', models.IntegerField()),
                ('game_observable', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
