# Generated by Django 4.1 on 2023-08-30 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePrefs',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('sel_type_01', models.IntegerField()),
                ('sel_type_02', models.IntegerField()),
                ('sel_type_03', models.IntegerField()),
                ('human_player_cnt', models.IntegerField(default=1)),
                ('game_observable', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndivGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=128, unique=True)),
                ('initiator_name', models.CharField(blank=True, max_length=128, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='active', max_length=19)),
                ('human_player_cnt', models.IntegerField(default=1)),
                ('game_observable', models.BooleanField(default=False)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(blank=True, max_length=128, null=True)),
                ('player_id_display', models.IntegerField()),
                ('player_type', models.CharField(max_length=16)),
                ('profile', models.CharField(max_length=16)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='Pricing.indivgames')),
                ('player_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participating_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
