# Generated by Django 4.1 on 2023-09-01 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('sequence_number', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('game_id', models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='Pricing.indivgames')),
            ],
            options={
                'ordering': ['-sequence_number'],
            },
        ),
    ]
