# Generated by Django 4.1 on 2023-10-22 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pricing', '0002_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('written_premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('in_force', models.DecimalField(decimal_places=2, max_digits=10)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pricing.indivgames')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
