# Generated by Django 4.1 on 2023-10-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0003_financials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financials',
            name='in_force',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
