# Generated by Django 4.1 on 2023-10-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0004_alter_financials_in_force'),
    ]

    operations = [
        migrations.AddField(
            model_name='financials',
            name='player_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
