# Generated by Django 4.1 on 2023-10-22 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0005_financials_player_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financials',
            old_name='game_id',
            new_name='game',
        ),
    ]
