# Generated by Django 4.1 on 2023-10-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0006_rename_game_id_financials_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financials',
            name='in_force',
            field=models.DecimalField(decimal_places=53, max_digits=53),
        ),
        migrations.AlterField(
            model_name='financials',
            name='written_premium',
            field=models.DecimalField(decimal_places=53, max_digits=53),
        ),
    ]
