# Generated by Django 4.1 on 2023-10-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0007_alter_financials_in_force_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financials',
            name='in_force',
            field=models.DecimalField(decimal_places=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='financials',
            name='written_premium',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
    ]
