# Generated by Django 4.1 on 2023-10-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0009_alter_financials_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='financials',
            name='mktg_expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
            preserve_default=False,
        ),
    ]
