# Generated by Django 4.1 on 2023-10-28 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pricing', '0010_financials_mktg_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='MktgSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(blank=True, max_length=128, null=True)),
                ('year', models.IntegerField()),
                ('beg_in_force', models.DecimalField(decimal_places=0, max_digits=16)),
                ('mktg_expense', models.DecimalField(decimal_places=2, max_digits=18)),
                ('mktg_expense_ind', models.DecimalField(decimal_places=2, max_digits=18)),
                ('end_in_force', models.DecimalField(decimal_places=0, max_digits=16)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pricing.indivgames')),
                ('player_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
