# Generated by Django 4.1 on 2023-11-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0011_mktgsales'),
    ]

    operations = [
        migrations.AddField(
            model_name='financials',
            name='inv_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
            preserve_default=False,
        ),
    ]
