# Generated by Django 4.1 on 2023-11-04 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0012_financials_inv_income'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financials',
            old_name='mktg_expense',
            new_name='annual_expenses',
        ),
    ]
