# Generated by Django 4.1 on 2023-11-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0013_rename_mktg_expense_financials_annual_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='financials',
            name='cy_losses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
            preserve_default=False,
        ),
    ]
