# Generated by Django 4.1 on 2023-11-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0014_financials_cy_losses'),
    ]

    operations = [
        migrations.AddField(
            model_name='financials',
            name='py_devl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
            preserve_default=False,
        ),
    ]
