# Generated by Django 4.1 on 2023-11-11 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0015_financials_py_devl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financials',
            old_name='cy_losses',
            new_name='ay_losses',
        ),
    ]
