# Generated by Django 4.1 on 2023-11-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0016_rename_cy_losses_financials_ay_losses'),
    ]

    operations = [
        migrations.AddField(
            model_name='financials',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
            preserve_default=False,
        ),
    ]
