# Generated by Django 4.1 on 2023-11-11 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0018_financials_capital_financials_capital_ratio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financials',
            old_name='dividend',
            new_name='dividend_paid',
        ),
    ]
