# Generated by Django 4.1 on 2023-11-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0019_rename_dividend_financials_dividend_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='mktgsales',
            name='avg_prem',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mktgsales',
            name='canx',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mktgsales',
            name='quotes',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mktgsales',
            name='sales',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=16),
            preserve_default=False,
        ),
    ]
