# Generated by Django 4.1 on 2023-11-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0020_mktgsales_avg_prem_mktgsales_canx_mktgsales_quotes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mktgsales',
            name='avg_prem',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
    ]
