# Generated by Django 4.1 on 2023-11-26 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pricing', '0021_alter_mktgsales_avg_prem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(blank=True, max_length=128, null=True)),
                ('year', models.IntegerField()),
                ('written_premium', models.DecimalField(decimal_places=2, max_digits=18)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pricing.indivgames')),
                ('player_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
