# Generated by Django 4.1 on 2023-11-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0022_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='annual_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='industry',
            name='capital',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='industry',
            name='capital_ratio',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='industry',
            name='capital_test',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='industry',
            name='cy_losses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='industry',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
            preserve_default=False,
        ),
    ]
