# Generated by Django 4.1 on 2023-11-26 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0023_industry_annual_expenses_industry_capital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mktgsales',
            name='mkt_in_force',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=16),
            preserve_default=False,
        ),
    ]
