# Generated by Django 4.1 on 2023-11-27 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0024_mktgsales_mkt_in_force'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mktgsales',
            old_name='mkt_in_force',
            new_name='in_force_ind',
        ),
    ]
