# Generated by Django 4.1 on 2023-12-03 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pricing', '0025_rename_mkt_in_force_mktgsales_in_force_ind'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(blank=True, max_length=128, null=True)),
                ('year', models.IntegerField()),
                ('beg_in_force', models.DecimalField(decimal_places=0, max_digits=16)),
                ('in_force', models.DecimalField(decimal_places=0, max_digits=16)),
                ('start_capital', models.DecimalField(decimal_places=2, max_digits=18)),
                ('excess_capital', models.DecimalField(decimal_places=2, max_digits=18)),
                ('capital', models.DecimalField(decimal_places=2, max_digits=18)),
                ('dividend_paid', models.DecimalField(decimal_places=2, max_digits=18)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=18)),
                ('inv_rate', models.DecimalField(decimal_places=6, max_digits=18)),
                ('irr_rate', models.DecimalField(decimal_places=6, max_digits=18)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pricing.indivgames')),
                ('player_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Decisions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(blank=True, max_length=128, null=True)),
                ('year', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pricing.indivgames')),
                ('player_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
