# Generated by Django 4.1 on 2023-12-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0027_indications'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuation',
            name='pv_index',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18),
            preserve_default=False,
        ),
    ]
