# Generated by Django 4.1 on 2023-12-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0029_triangles'),
    ]

    operations = [
        migrations.AddField(
            model_name='financials',
            name='clm_bi',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financials',
            name='clm_cl',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=16),
            preserve_default=False,
        ),
    ]
