# Generated by Django 4.1 on 2023-12-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0030_financials_clm_bi_financials_clm_cl'),
    ]

    operations = [
        migrations.AddField(
            model_name='triangles',
            name='claim_trend',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
    ]
