# Generated by Django 4.1 on 2023-12-27 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0031_triangles_claim_trend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triangles',
            name='claim_trend',
        ),
        migrations.CreateModel(
            name='ClaimTrends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_trend', models.JSONField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pricing.indivgames')),
            ],
        ),
    ]
