# Generated by Django 4.1 on 2023-12-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0032_remove_triangles_claim_trend_claimtrends'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimtrends',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
