# Generated by Django 4.1 on 2023-12-27 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0033_claimtrends_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claimtrends',
            old_name='claim_trend',
            new_name='claim_trends',
        ),
    ]
