# Generated by Django 4.1 on 2023-12-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0034_rename_claim_trend_claimtrends_claim_trends'),
    ]

    operations = [
        migrations.AddField(
            model_name='indications',
            name='indication_data',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
    ]
