# Generated by Django 4.1 on 2023-12-31 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0036_decisions_decisions_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisions',
            name='decisions_locked',
            field=models.BooleanField(default=False),
        ),
    ]
