# Generated by Django 4.1 on 2023-12-31 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0037_decisions_decisions_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisions',
            name='decisions_game_stage',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
