# Generated by Django 4.1 on 2023-12-31 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0038_decisions_decisions_game_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisions',
            name='decisions_time_stamp',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
    ]
