# Generated by Django 4.1 on 2024-01-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0039_decisions_decisions_time_stamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decisions',
            name='decisions_data',
        ),
        migrations.AddField(
            model_name='decisions',
            name='sel_aa_margin',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='decisions',
            name='sel_aa_margin_max',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='decisions',
            name='sel_aa_margin_min',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='decisions',
            name='sel_avg_prem',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='decisions',
            name='sel_exp_ratio_data',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='decisions',
            name='sel_exp_ratio_data_max',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='decisions',
            name='sel_exp_ratio_data_min',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='decisions',
            name='sel_exp_ratio_mktg',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='decisions',
            name='sel_exp_ratio_mktg_max',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='decisions',
            name='sel_exp_ratio_mktg_min',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='decisions',
            name='sel_loss_trend_margi_min',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='decisions',
            name='sel_loss_trend_margin',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='decisions',
            name='sel_loss_trend_margin_max',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='decisions',
            name='sel_profit_margin',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='decisions',
            name='sel_profit_margin_max',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='decisions',
            name='sel_profit_margin_min',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
