# Generated by Django 4.1 on 2024-01-01 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0040_remove_decisions_decisions_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decisions',
            old_name='sel_loss_trend_margi_min',
            new_name='sel_loss_trend_margin_min',
        ),
    ]
