# Generated by Django 4.1 on 2024-01-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0041_rename_sel_loss_trend_margi_min_decisions_sel_loss_trend_margin_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisions',
            name='curr_avg_prem',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='decisions',
            name='server_indic_avg_prem',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
            preserve_default=False,
        ),
    ]
