# Generated by Django 4.1 on 2024-01-07 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0042_decisions_curr_avg_prem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decisions',
            name='server_indic_avg_prem',
        ),
    ]
