# Generated by Django 4.1 on 2024-01-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0043_remove_decisions_server_indic_avg_prem'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprefs',
            name='default_selection_type',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
