# Generated by Django 4.1 on 2025-05-31 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pricing', '0048_lock_user_alter_lock_lock_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprefs',
            name='game_difficulty',
            field=models.CharField(default='Novice', max_length=10),
        ),
    ]
